config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "welcome#index"
  resources :items
  resources :warehouses, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :warehouse

  def warehouse_name
    warehouse.name
  end
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all
  end

  def show
    @item
  end

  def new
    @item = Item.new
  end

  def create
    item = Item.create(item_params)
    item.save

    redirect_to items_path, notice: "#{item.name} created successfully."
  end

  def edit
    @item
  end

  def update
    @item.update(item_params)
    @item.save

    redirect_to item_path(@item.id), notice: "Item updated successfully."
  end

  def destroy
    @item.destroy

    redirect_to items_path, notice: "Item destroyed successfully."
  end

  private

  def set_item
    if Item.exists?(params[:id])
      @item = Item.find(params[:id])
    else
      redirect_to items_path, alert: "Item does not exist."
    end
  end

  def item_params
    params.require(:item).permit(:name, :quantity, :warehouse_id)
  end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :set_warehouse, only: [:show, :edit, :update]
  
  def index
    @warehouses = Warehouse.all
  end

  def show
    @warehouse
  end

  def new
    @warehouse = Warehouse.new
  end

  def create
    warehouse = Warehouse.create(warehouse_params)
    warehouse.save

    redirect_to warehouses_path, notice: "#{warehouse.name} created successfully."
  end

  def edit
    @warehouse
  end

  def update
    @warehouse.update(warehouse_params)
    @warehouse.save

    redirect_to warehouse_path(@warehouse.id), notice: "Warehouse updated successfully."
  end

  private

  def set_warehouse
    if Warehouse.exists?(params[:id])
      @warehouse = Warehouse.find(params[:id])
    else
      redirect_to warehouses_path, alert: "Warehouse does not exist."
    end
  end

  def warehouse_params
    params.require(:warehouse).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.erb
<%= form_with model: model, method: method, local: true do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name, required: true%><br><br>

  <%= form.label :quantity %>
  <%= form.number_field :quantity, required: true %><br><br>

  <%= form.label :warehouse_id %>
  <%= form.collection_select :warehouse_id, Warehouse.order(:name), :id, :name %><br><br>

  <%= form.submit button_text %>
<% end %>

app/views/items/edit.html.erb
<h1>Edit Inventory Item</h1>

<%= render partial: 'form', locals: {
  model: @item,
  method: :patch,
  button_text: 'Edit Item'
} %>
<br>

<%= link_to 'Back', item_path(@item.id) %>

app/views/items/index.html.erb
<h1>Inventory Items</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Quantity</th>
    <th>Warehouse</th>
  </tr>
  <% @items.each do |item| %>
    <tr id="item-<%= item.id %>">
      <td><%= link_to "#{item.name}", item_path(item.id) %></td>
      <td><%= item.quantity %></td>
      <td><%= item.warehouse_name %></td>
    </tr>
  <% end %>
</table>
<br>

<%= link_to 'Create Item', new_item_path %>

app/views/items/new.html.erb
<h1>Create an Inventory Item</h1>

<%= render partial: 'form', locals: {
  model: @item,
  method: :post,
  button_text: 'Create Item'
} %>
<br>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<h1>Item</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Quantity</th>
    <th colspan='2'></th>
  </tr>
  <tr id="item-<%= @item.id %>">
    <td><%= @item.name %></td>
    <td><%= @item.quantity %></td>
    <td><%= link_to 'Edit', edit_item_path(@item.id) %></td>
    <td><%= link_to 'Delete', item_path(@item.id), method: :delete %></td>
  </tr>
</table>
<br>

<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRuby3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= link_to 'Home', root_path %>
    <% flash.each do |type, msg| %>
      <div><%= msg %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/warehouses/_form.html.erb
<%= form_with model: model, method: method, local: true do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name, required: true%><br><br>

  <%= form.submit button_text %>
<% end %>

app/views/warehouses/edit.html.erb
<h1>Edit Warehouse</h1>

<%= render partial: 'form', locals: {
  model: @warehouse,
  method: :patch,
  button_text: 'Edit Warehouse'
} %>
<br>

<%= link_to 'Back', warehouses_path %>

app/views/warehouses/index.html.erb
<h1>Warehouses</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
  </tr>
  <% @warehouses.each do |warehouse| %>
    <tr id="warehouse-<%= warehouse.id %>">
      <td><%= link_to "#{warehouse.name}", warehouse_path(warehouse.id) %></td>
      <td><%= link_to 'Edit', edit_warehouse_path(warehouse.id) %></td>
    </tr>
  <% end %>
</table>
<br>

<%= link_to 'Create Warehouse', new_warehouse_path %>

app/views/warehouses/new.html.erb
<h1>Create a Warehouse</h1>

<%= render partial: 'form', locals: {
  model: @warehouse,
  method: :post,
  button_text: 'Create Warehouse'
} %>
<br>

<%= link_to 'Back', warehouses_path %>

app/views/warehouses/show.html.erb
<h1><%= @warehouse.name %></h1>

<table>
  <tr>
    <th>Name</th>
    <th>Quantity</th>
  </tr>
  <% @warehouse.items.each do |item| %>
    <tr>
      <td><%= item.name %></td>
      <td><%= item.quantity %></td>
    </tr>
  <% end %>
</table>
<br>

<%= link_to 'Back', warehouses_path %>

app/views/welcome/index.html.erb
<h1>Inventory</h1>

<%= link_to 'Items', items_path %>
<%= link_to 'Warehouses', warehouses_path %>